on:
  push:

name: Flatpak
jobs:
  metainfo:
    name: "Validate metainfo"
    runs-on: ubuntu-latest
    steps:
      - name: Install flatpak
        run: |
          sudo apt-get update && sudo apt-get install flatpak
          sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install -y org.flatpak.Builder
      - name: checkout
        uses: actions/checkout@v4
      - name: flatpak-builder-lint
        run: flatpak run --command=flatpak-builder-lint org.flatpak.Builder appstream  data/org.scratchmark.Scratchmark.metainfo.xml
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: flatpak-cargo-generator
        working-directory: build-aux
        run: |
          curl -o flatpak-cargo-generator.py https://raw.githubusercontent.com/flatpak/flatpak-builder-tools/refs/heads/master/cargo/flatpak-cargo-generator.py
          python3 flatpak-cargo-generator.py ../Cargo.lock -o generated-sources.json
      - name: Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: Scratchmark.flatpak
          manifest-path: build-aux/org.scratchmark.Scratchmark.yml
          cache-key: flatpak-builder-${{ github.sha }}
  release:
    name: "Generate Release"
    needs: 
      - "flatpak"
      - "metainfo"
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check if prerelase
        run: |
          if [[ ${{ github.ref_name }} =~ -(alpha|beta|rc) ]]
          then
            echo "PRERELEASE=true" >> $GITHUB_ENV
          else
            echo "PRERELEASE=false" >> $GITHUB_ENV
          fi
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: Scratchmark-x86_64.flatpak
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: Scratchmark.flatpak
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ env.PRERELEASE }}
          body: "Release contains an x86_64 Flatpak."
          generateReleaseNotes: true
          artifactErrorsFailBuild: true
